<?php
// Generated by ZF2's ./bin/classmap_generator.php @ Sun, 15 Jan 2012 19:44:21 -0700
return array(
    'ZfcUserDoctrineMongoODM\Module'                            => __DIR__ . '/Module.php',
    'ZfcUserDoctrineMongoODM\Document\UserMappedSuperClass'     => __DIR__ . '/src/ZfcUserDoctrineMongoODM/Document/UserMappedSuperClass.php',
    'ZfcUserDoctrineMongoODM\Document\UserMetaMappedSuperClass' => __DIR__ . '/src/ZfcUserDoctrineMongoODM/Document/UserMetaMappedSuperClass.php',
    'ZfcUserDoctrineMongoODM\Document\UserMeta'                 => __DIR__ . '/src/ZfcUserDoctrineMongoODM/Document/UserMeta.php',
    'ZfcUserDoctrineMongoODM\Document\User'                     => __DIR__ . '/src/ZfcUserDoctrineMongoODM/Document/User.php',
    'ZfcUserDoctrineMongoODM\Event\ResolveTargetEntityListener' => __DIR__ . '/src/ZfcUserDoctrineMongoODM/Event/ResolveTargetEntityListener.php',
    'ZfcUserDoctrineMongoODM\Mapper\UserMetaMongoDB'            => __DIR__ . '/src/ZfcUserDoctrineMongoODM/Mapper/UserMetaMongoDB.php',
    'ZfcUserDoctrineMongoODM\Mapper\UserMongoDB'                => __DIR__ . '/src/ZfcUserDoctrineMongoODM/Mapper/UserMongoDB.php',
);